#!/usr/bin/env bash
# Displays numbers from 1-100, replacing multiples of 3 with "Fizz", multiples
# of 5 with "Buzz" and multiples of both 3 and 5 with "FizzBuzz"

i="1"

while [ $i -lt 101 ]
do
    if ((i % 3 == 0 && i % 5 == 0))
    then
	echo "FizzBuzz"

    elif ((i % 3 == 0))
    then
	echo "Fizz"

    elif ((i % 5 == 0))
    then
	echo "Buzz"

    else
	echo "$i"

    fi

    ((i++))

done
